spring.application.name=cscb2026-pharmacy
server.port=8084
spring.datasource.url=jdbc:mysql://localhost/pharmacy-app-demo-2026?createDatabaseIfNotExist=true&useSSL=true
spring.datasource.username=education_user
spring.datasource.password=education_user
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.format_sql=true
logging.level.org.hibernate.orm.jdbc.bind=TRACE
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.springframework=DEBUG

